
server:
  port: 8769
spring:
  application:
    name: spring-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10002/eureka/
zuul:
  routes:
    api-a:
      path: /api-member/**
      service-id: service-member
    api-b:
      path: /api-order/**
      service-id: service-order